const actionTypes = {
  login: {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
    FAILURE: 'LOGIN_FAILURE'
  },
  logout: {
    REQUEST: 'LOGOUT_REQUEST',
    SUCCESS: 'LOGOUT_SUCCESS',
    FAILURE: 'LOGOUT_FAILURE'
  },
  registration: {
    REQUEST: 'REGISTRATION_REQUEST',
    SUCCESS: 'REGISTRATION_SUCCESS',
    FAILURE: 'REGISTRATION_FAILURE'
  },
  timeline: {
    REQUEST: 'TIMELINE_ITEMS_REQUEST',
    RECEIVED: 'TIMELINE_ITEMS_RECEIVED',
    FAILURE: 'TIMELINE_ITEMS_FAILURE',
    UPDATE_FILTER: 'FILTER_CRITERIA_UPDATE'
  },
  userData: {
    UPDATED: 'USER_DATA_UPDATED'
  },
  vote: {
    SENT: 'EVENT_VOTE_SENT',
    CASTED: 'EVENT_VOTE_CASTED',
    FAILURE: 'EVENT_VOTE_FAILURE',
    RESULTS_REQUEST: 'VOTE RESULTS REQUEST',
    RESULTS_SUCCESS: 'VOTE RESULTS SUCCESS',
    RESULTS_FAILURE: 'VOTE RESULTS FAILURE'
  }
}

export default actionTypes
